FROM node:18-alpine

# Establecer directorio de trabajo
WORKDIR /usr/src/app

# Copiar archivos del frontend
COPY . .

# Instalar dependencias
RUN npm install

# Puerto
EXPOSE 4200

CMD ["npm", "start"]
