FROM node:18 AS build

WORKDIR /usr/src/app

# Copiar package.json primero
COPY package*.json ./
RUN npm install

# Copiar el resto de archivos
COPY . .

# Asegurarse de que la carpeta environments existe y está correcta
RUN ls -la src/environments || exit 1

# Build con configuración de producción explícita
RUN npm run build -- --configuration=production

FROM nginx:latest
COPY --from=build /usr/src/app/dist/frontend/browser /usr/share/nginx/html
EXPOSE 80