FROM node:20-alpine

WORKDIR /usr/src/app

# Instalar Angular CLI globalmente
RUN npm install -g @angular/cli@19

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código fuente
COPY . .

EXPOSE 4200

# Comando para servir la aplicación
CMD ["ng", "serve", "--host", "0.0.0.0", "--disable-host-check"]