version: "3.8"

services:
  laravel:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: always
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - COMPOSER_ALLOW_SUPERUSER=1
    volumes:
      - ./backend:/var/www/html
      #- /var/www/html/vendor
      #- /var/www/html/storage
    depends_on:
      - db

  angular:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular_app
    restart: always
    ports:
      - "4200:80"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist

  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./backend:/var/www/html
    depends_on:
      - laravel
      - angular

  db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: medicare
      MYSQL_USER: medicare_user
      MYSQL_PASSWORD: medicare_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data: {}
