version: "3.9"

services:
  db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: medicare
      MYSQL_USER: medicare_user
      MYSQL_PASSWORD: medicare_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: medicare_backend
    environment:
      APP_NAME: Laravel
      APP_ENV: local
      APP_KEY: base64:5hHdJC5Y+qvIeTD4j0uIMfeDrMONNEyoQ69y//E83s0=
      APP_DEBUG: "true"
      APP_URL: http://localhost
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: medicare
      DB_USERNAME: medicare_user
      DB_PASSWORD: medicare_password
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: medicare_frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/usr/src/app
    working_dir: /usr/src/app
    command: npm start
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    container_name: medicare_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend

volumes:
  db_data:
