version: "3.8"

services:
  laravel:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: always
    volumes:
      - ./backend:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    depends_on:
      - db

  angular:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular_app
    restart: always
    stdin_open: true
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/usr/src/app
    command: npm start

  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./backend:/var/www/html
    depends_on:
      - laravel

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: medicare
      MYSQL_USER: medicare_user
      MYSQL_PASSWORD: medicare_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
